# Generated by Django 3.1.6 on 2021-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('User', 'User'), ('Specialist', 'Specialist')], default='User', max_length=10),
        ),
    ]
