# Generated by Django 3.1.6 on 2021-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
