# Generated by Django 3.1.6 on 2021-08-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_question_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Education', 'Education'), ('Home', 'Home'), ('General', 'General')], default='General', max_length=12),
        ),
    ]
