# Generated by Django 3.1.6 on 2021-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_auto_20210813_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
