# Generated by Django 3.1.6 on 2021-08-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0010_question_progress_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='field',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Education', 'Education'), ('Home', 'Home'), ('General', 'General')], default='General', max_length=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='progress_type',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Archived', 'Archived')], default='Pending', max_length=12),
        ),
    ]
