# Generated by Django 3.1.6 on 2021-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='specialist',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rooms',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
