# Generated by Django 3.1.6 on 2021-08-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0013_auto_20210819_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.question'),
        ),
    ]
