# Generated by Django 3.1.6 on 2021-08-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_rooms_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='room',
            field=models.CharField(default='', max_length=6),
        ),
    ]
