# Generated by Django 3.1.6 on 2021-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0017_auto_20210819_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='235AAX', max_length=6),
        ),
    ]
