# Generated by Django 3.1.6 on 2021-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0018_auto_20210819_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='QJ1LYY', max_length=6, primary_key=True, serialize=False),
        ),
    ]
