# Generated by Django 3.1.6 on 2021-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0021_auto_20210820_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='creator_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='AYJ55A', max_length=6, primary_key=True, serialize=False),
        ),
    ]
