# Generated by Django 3.1.6 on 2021-08-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0022_auto_20210820_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='AD5GP0', max_length=6, primary_key=True, serialize=False),
        ),
    ]
