# Generated by Django 3.1.6 on 2021-08-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0023_auto_20210822_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='progress_type',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('Disputed', 'Disputed')], default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='FLOFHM', max_length=6, primary_key=True, serialize=False),
        ),
    ]
