# Generated by Django 3.1.6 on 2021-08-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0024_auto_20210827_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='372SY9', max_length=6, primary_key=True, serialize=False),
        ),
    ]
